apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    acornsoft.io/workload-group-no: "9"
  labels:
    app: com-singleapp
  name: com-singleapp
  namespace: uni-edu
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: com-singleapp
  template:
    metadata:
      annotations:
        cocktail-deploy-datetime: "2023-01-26 08:07:12.154"
        sidecar.istio.io/inject: "false"
      labels:
        app: com-singleapp
    spec:
      containers:
      - image: 192.168.100.12/uni-edu/commerce-single:v2
        imagePullPolicy: Always
        name: com-singleapp
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: commerce-cocktail-t8ceb0dry5v7
